"""Report generation service for threats and ASR rules."""

import io
from datetime import datetime
from typing import Dict, Any, List, Optional
from dataclasses import dataclass

# HTML template for threat reports
THREAT_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Threat Report: {threat_name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f5f5f7; padding: 2rem; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow: hidden; }}
        .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #2d2d44 100%); color: white; padding: 2rem; }}
        .header h1 {{ font-size: 1.5rem; margin-bottom: 0.5rem; word-break: break-all; }}
        .header .meta {{ opacity: 0.8; font-size: 0.9rem; }}
        .badge {{ display: inline-block; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.75rem; font-weight: 600; margin-right: 0.5rem; }}
        .badge-category {{ background: #6366f1; color: white; }}
        .badge-family {{ background: #22c55e; color: white; }}
        .section {{ padding: 1.5rem 2rem; border-bottom: 1px solid #e5e5e5; }}
        .section:last-child {{ border-bottom: none; }}
        .section h2 {{ font-size: 1.1rem; color: #1a1a2e; margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem; }}
        .section h2::before {{ content: ''; width: 4px; height: 20px; background: #6366f1; border-radius: 2px; }}
        .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; }}
        .stat-card {{ background: #f8f9fa; padding: 1rem; border-radius: 8px; text-align: center; }}
        .stat-value {{ font-size: 1.5rem; font-weight: 700; color: #1a1a2e; }}
        .stat-label {{ font-size: 0.8rem; color: #666; text-transform: uppercase; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
        th, td {{ padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e5e5; }}
        th {{ background: #f8f9fa; font-weight: 600; color: #444; }}
        .string-content {{ font-family: 'Monaco', 'Menlo', monospace; font-size: 0.85rem; background: #f1f5f9; padding: 0.25rem 0.5rem; border-radius: 4px; word-break: break-all; }}
        .hex-preview {{ font-family: 'Monaco', 'Menlo', monospace; font-size: 0.8rem; background: #1a1a2e; color: #22c55e; padding: 1rem; border-radius: 8px; overflow-x: auto; white-space: pre; }}
        .yara-rule {{ font-family: 'Monaco', 'Menlo', monospace; font-size: 0.85rem; background: #1a1a2e; color: #f8f9fa; padding: 1rem; border-radius: 8px; overflow-x: auto; white-space: pre-wrap; }}
        .footer {{ background: #f8f9fa; padding: 1rem 2rem; text-align: center; font-size: 0.8rem; color: #666; }}
        .risk-critical {{ color: #dc2626; }}
        .risk-high {{ color: #ea580c; }}
        .risk-medium {{ color: #ca8a04; }}
        .risk-low {{ color: #16a34a; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{threat_name}</h1>
            <div class="meta">
                <span class="badge badge-category">{category}</span>
                <span class="badge badge-family">{family}</span>
                <br><br>
                Signature ID: 0x{signature_id:08X} | Generated: {generated_date}
            </div>
        </div>

        <div class="section">
            <h2>Overview</h2>
            <div class="stat-grid">
                <div class="stat-card">
                    <div class="stat-value">{signature_count}</div>
                    <div class="stat-label">Signatures</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{string_count}</div>
                    <div class="stat-label">String Patterns</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{binary_count}</div>
                    <div class="stat-label">Binary Patterns</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{lua_script_count}</div>
                    <div class="stat-label">Lua Scripts</div>
                </div>
            </div>
        </div>

        {signatures_section}

        {strings_section}

        {yara_section}

        <div class="footer">
            Generated by Defender Explorer | {generated_date}
        </div>
    </div>
</body>
</html>
"""

SIGNATURES_SECTION_TEMPLATE = """
<div class="section">
    <h2>Signature Types</h2>
    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Count</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
</div>
"""

STRINGS_SECTION_TEMPLATE = """
<div class="section">
    <h2>Detected Strings ({count})</h2>
    <table>
        <thead>
            <tr>
                <th>String</th>
                <th>Type</th>
                <th>Classification</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
</div>
"""

YARA_SECTION_TEMPLATE = """
<div class="section">
    <h2>YARA Rule</h2>
    <div class="yara-rule">{yara_content}</div>
</div>
"""

# HTML template for ASR reports
ASR_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ASR Rule Report: {rule_name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; background: #f5f5f7; padding: 2rem; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow: hidden; }}
        .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #2d2d44 100%); color: white; padding: 2rem; }}
        .header h1 {{ font-size: 1.3rem; margin-bottom: 0.5rem; }}
        .header .meta {{ opacity: 0.8; font-size: 0.9rem; }}
        .header .guid {{ font-family: monospace; background: rgba(255,255,255,0.1); padding: 0.25rem 0.5rem; border-radius: 4px; }}
        .section {{ padding: 1.5rem 2rem; border-bottom: 1px solid #e5e5e5; }}
        .section:last-child {{ border-bottom: none; }}
        .section h2 {{ font-size: 1.1rem; color: #1a1a2e; margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem; }}
        .section h2::before {{ content: ''; width: 4px; height: 20px; background: #6366f1; border-radius: 2px; }}
        .description {{ background: #f8f9fa; padding: 1rem; border-radius: 8px; font-size: 0.95rem; }}
        .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; }}
        .stat-card {{ background: #f8f9fa; padding: 1rem; border-radius: 8px; text-align: center; }}
        .stat-value {{ font-size: 1.5rem; font-weight: 700; color: #1a1a2e; }}
        .stat-label {{ font-size: 0.8rem; color: #666; text-transform: uppercase; }}
        .pattern-list {{ list-style: none; }}
        .pattern-list li {{ padding: 0.5rem 0.75rem; background: #f1f5f9; margin-bottom: 0.5rem; border-radius: 6px; font-family: monospace; font-size: 0.85rem; display: flex; justify-content: space-between; align-items: center; }}
        .risk-badge {{ padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }}
        .risk-critical {{ background: #fef2f2; color: #dc2626; }}
        .risk-high {{ background: #fff7ed; color: #ea580c; }}
        .risk-medium {{ background: #fefce8; color: #ca8a04; }}
        .risk-low {{ background: #f0fdf4; color: #16a34a; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
        th, td {{ padding: 0.75rem; text-align: left; border-bottom: 1px solid #e5e5e5; }}
        th {{ background: #f8f9fa; font-weight: 600; color: #444; }}
        .mitre-tag {{ display: inline-block; padding: 0.25rem 0.5rem; background: #dbeafe; color: #1d4ed8; border-radius: 4px; font-size: 0.8rem; margin: 0.25rem; }}
        .footer {{ background: #f8f9fa; padding: 1rem 2rem; text-align: center; font-size: 0.8rem; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{rule_name}</h1>
            <div class="meta">
                <span class="guid">{guid}</span>
                <br><br>
                Generated: {generated_date}
            </div>
        </div>

        <div class="section">
            <h2>Description</h2>
            <div class="description">{description}</div>
        </div>

        <div class="section">
            <h2>Overview</h2>
            <div class="stat-grid">
                <div class="stat-card">
                    <div class="stat-value">{script_count}</div>
                    <div class="stat-label">Lua Scripts</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{exclusion_count}</div>
                    <div class="stat-label">Exclusions</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{process_count}</div>
                    <div class="stat-label">Processes</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value risk-{overall_risk}">{overall_risk}</div>
                    <div class="stat-label">Risk Level</div>
                </div>
            </div>
        </div>

        {exclusions_section}

        {processes_section}

        {mitre_section}

        {related_rules_section}

        <div class="footer">
            Generated by Defender Explorer | {generated_date}
        </div>
    </div>
</body>
</html>
"""


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#x27;"))


def generate_threat_report_html(
    threat_data: Dict[str, Any],
    signatures_data: Dict[str, Any],
    yara_rule: Optional[str] = None,
) -> str:
    """
    Generate an HTML report for a threat.

    Args:
        threat_data: Threat details
        signatures_data: Classified signatures data
        yara_rule: Optional generated YARA rule

    Returns:
        HTML string
    """
    # Build signatures section
    sig_types = threat_data.get("signature_types", {})
    sig_rows = ""
    for sig_type, count in sorted(sig_types.items(), key=lambda x: -x[1]):
        sig_rows += f"<tr><td>{escape_html(sig_type)}</td><td>{count}</td><td>-</td></tr>\n"

    signatures_section = ""
    if sig_rows:
        signatures_section = SIGNATURES_SECTION_TEMPLATE.format(rows=sig_rows)

    # Build strings section
    string_sigs = signatures_data.get("string_signatures", [])
    string_rows = ""
    for sig in string_sigs[:50]:  # Limit to 50 strings
        content = escape_html(sig.get("content", "")[:100])
        sig_type = escape_html(sig.get("sig_type_name", "Unknown"))
        classification = sig.get("classification", "string")
        string_rows += f"<tr><td><span class='string-content'>{content}</span></td><td>{sig_type}</td><td>{classification}</td></tr>\n"

    strings_section = ""
    if string_rows:
        strings_section = STRINGS_SECTION_TEMPLATE.format(
            count=len(string_sigs),
            rows=string_rows
        )

    # Build YARA section
    yara_section = ""
    if yara_rule:
        yara_section = YARA_SECTION_TEMPLATE.format(
            yara_content=escape_html(yara_rule)
        )

    # Generate final HTML
    html = THREAT_REPORT_TEMPLATE.format(
        threat_name=escape_html(threat_data.get("threat_name", "Unknown")),
        category=escape_html(threat_data.get("category", "Unknown")),
        family=escape_html(threat_data.get("family", "Unknown")),
        signature_id=threat_data.get("signature_id", 0),
        generated_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        signature_count=threat_data.get("signature_count", 0),
        string_count=signatures_data.get("string_count", 0),
        binary_count=signatures_data.get("binary_count", 0),
        lua_script_count=len(threat_data.get("lua_scripts", [])),
        signatures_section=signatures_section,
        strings_section=strings_section,
        yara_section=yara_section,
    )

    return html


def generate_asr_report_html(
    rule_data: Dict[str, Any],
    exclusion_analysis: Dict[str, Any],
    related_rules: List[Dict[str, Any]],
) -> str:
    """
    Generate an HTML report for an ASR rule.

    Args:
        rule_data: ASR rule details
        exclusion_analysis: Exclusion impact analysis
        related_rules: Related rules by shared exclusions

    Returns:
        HTML string
    """
    extracted = rule_data.get("extracted_data", {})

    # Build exclusions section
    exclusion_paths = extracted.get("exclusion_paths", [])
    path_analyses = exclusion_analysis.get("path_analyses", [])

    exclusions_html = ""
    if exclusion_paths:
        items = ""
        for i, path in enumerate(exclusion_paths):
            risk = "low"
            if i < len(path_analyses):
                risk = path_analyses[i].get("risk_level", "low")
            items += f'<li>{escape_html(path)} <span class="risk-badge risk-{risk}">{risk}</span></li>\n'
        exclusions_html = f"""
        <div class="section">
            <h2>Exclusion Paths ({len(exclusion_paths)})</h2>
            <ul class="pattern-list">{items}</ul>
        </div>
        """

    # Build processes section
    processes = extracted.get("process_names", [])
    process_analyses = exclusion_analysis.get("process_analyses", [])

    processes_html = ""
    if processes:
        items = ""
        for i, proc in enumerate(processes):
            risk = "low"
            if i < len(process_analyses):
                risk = process_analyses[i].get("risk_level", "low")
            items += f'<li>{escape_html(proc)} <span class="risk-badge risk-{risk}">{risk}</span></li>\n'
        processes_html = f"""
        <div class="section">
            <h2>Process Exclusions ({len(processes)})</h2>
            <ul class="pattern-list">{items}</ul>
        </div>
        """

    # Build MITRE section
    mitre = extracted.get("mitre_techniques", [])
    mitre_html = ""
    if mitre:
        tags = "".join(f'<span class="mitre-tag">{escape_html(t)}</span>' for t in mitre)
        mitre_html = f"""
        <div class="section">
            <h2>MITRE ATT&CK Techniques</h2>
            <div>{tags}</div>
        </div>
        """

    # Build related rules section
    related_html = ""
    if related_rules:
        rows = ""
        for rule in related_rules[:10]:
            shared = len(rule.get("shared_exclusions", [])) + len(rule.get("shared_processes", []))
            rows += f"""
            <tr>
                <td>{escape_html(rule.get('short_name', rule.get('rule_name', '')))}</td>
                <td>{shared}</td>
                <td><code>{escape_html(rule.get('rule_guid', ''))}</code></td>
            </tr>
            """
        related_html = f"""
        <div class="section">
            <h2>Related Rules</h2>
            <table>
                <thead>
                    <tr><th>Rule</th><th>Shared Items</th><th>GUID</th></tr>
                </thead>
                <tbody>{rows}</tbody>
            </table>
        </div>
        """

    # Get overall risk
    risk_summary = exclusion_analysis.get("risk_summary", {})
    overall_risk = risk_summary.get("overall_risk", "low")

    # Generate final HTML
    html = ASR_REPORT_TEMPLATE.format(
        rule_name=escape_html(rule_data.get("name", "Unknown")),
        guid=escape_html(rule_data.get("guid", "")),
        description=escape_html(rule_data.get("description", "No description available")),
        generated_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        script_count=rule_data.get("script_count", 0),
        exclusion_count=len(exclusion_paths),
        process_count=len(processes),
        overall_risk=escape_html(overall_risk),
        exclusions_section=exclusions_html,
        processes_section=processes_html,
        mitre_section=mitre_html,
        related_rules_section=related_html,
    )

    return html


def generate_pdf_from_html(html: str) -> bytes:
    """
    Generate PDF from HTML content.

    Requires weasyprint to be installed.

    Raises:
        RuntimeError: If weasyprint is not installed or PDF generation fails.
    """
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        raise RuntimeError(
            "PDF export requires weasyprint. "
            "Install it with: pip install weasyprint"
        )
    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {e}") from e
